version: '3.8'

services:
  postgres:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: music_user
      POSTGRES_PASSWORD: music_password
      POSTGRES_DB: music_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: music_user
      MONGO_INITDB_ROOT_PASSWORD: music_password
      MONGO_INITDB_DATABASE: music_db
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    ports:
      - "6380:6379"
    command: redis-server --requirepass music_password
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data: 